/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Consumer;

import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

/**
 *
 * @author itsta
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        gname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        conf_password = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        birthday = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel16 = new javax.swing.JLabel();
        meter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 210, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 280, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("LOGIN");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 749, 60, -1));

        submit.setBackground(new java.awt.Color(255, 204, 0));
        submit.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("REGISTER");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 280, 30));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 120, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Already have an account?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, 230, 20));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Account #");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));
        jPanel1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 280, 30));
        jPanel1.add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 280, 30));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Given name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, -1));
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 280, 30));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Middle name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 280, 30));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 280, 30));

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, -1));
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, 30));

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile #");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, -1));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 280, 30));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Birthday");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 150, -1));
        jPanel1.add(conf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 280, 30));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Confirm Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 150, -1));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Complete Address");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 150, -1));
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 280, 30));

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Meter #");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));
        jPanel1.add(meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 280, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        login loginFrame = new login();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
        // Validate inputs
        String Gname = gname.getText().trim();
        String Mname = mname.getText().trim();
        String Lname = lname.getText().trim();
        String Email = email.getText().trim();
        String Mobile = mobile.getText().trim();
        String Address = address.getText().trim();
        String Account = account.getText().trim();
        String MeterNo = meter.getText().trim(); // New meter number field
        String Password = new String(password.getPassword()).trim();
        String confPassword = new String(conf_password.getPassword()).trim();
        java.util.Date bday = birthday.getDate();

        // Input validation
        if (Gname.isEmpty() || Lname.isEmpty() || Email.isEmpty() || Mobile.isEmpty() || 
            Address.isEmpty() || Account.isEmpty() || MeterNo.isEmpty() || bday == null || Password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields except middle name are required.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate meter number format (alphanumeric, 8-15 characters)
        if (!MeterNo.matches("^[A-Za-z0-9]{8,15}$")) {
            JOptionPane.showMessageDialog(this, "Meter number must be 8-15 alphanumeric characters.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Rest of your validation checks...
        if (!Password.equals(confPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, "Invalid email format.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Long.parseLong(Mobile);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mobile number must be numeric.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Account.matches("\\d{6,12}")) {
            JOptionPane.showMessageDialog(this, "Invalid account number (must be 6-12 digits).", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Hash password
        String hashedPassword = BCrypt.hashpw(Password, BCrypt.gensalt());

        // Convert birthday to java.sql.Date
        java.sql.Date birthdaySql = new java.sql.Date(bday.getTime());
        
        String DB_URL = "jdbc:mysql://localhost:3306/aurelco";
        String DB_USER = "root";
        String DB_PASS = "";

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
            // Check for existing email, account, or meter number
            String checkQuery = "SELECT * FROM consumers WHERE email = ? OR account_no = ? OR meter_number = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            checkStmt.setString(1, Email);
            checkStmt.setString(2, Account);
            checkStmt.setString(3, MeterNo);
            ResultSet rs = checkStmt.executeQuery();
            
            if (rs.next()) {
                String errorMsg = "";
                if (rs.getString("email").equalsIgnoreCase(Email)) {
                    errorMsg = "Email already registered.";
                } else if (rs.getString("account_no").equals(Account)) {
                    errorMsg = "Account number already registered.";
                } else {
                    errorMsg = "Meter number already in use.";
                }
                JOptionPane.showMessageDialog(this, errorMsg, 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Insert new consumer with meter number
            String insertQuery = "INSERT INTO consumers (given_name, middle_name, last_name, " +
                               "email, mobile, address, account_no, meter_number, birthday, password) " +
                               "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(insertQuery);
            pstmt.setString(1, Gname);
            pstmt.setString(2, Mname);
            pstmt.setString(3, Lname);
            pstmt.setString(4, Email);
            pstmt.setString(5, Mobile);
            pstmt.setString(6, Address);
            pstmt.setString(7, Account);
            pstmt.setString(8, MeterNo);
            pstmt.setDate(9, birthdaySql);
            pstmt.setString(10, hashedPassword);

            int rows = pstmt.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Consumer registered successfully with meter number!", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                new login().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry") && ex.getMessage().contains("uk_consumers_meter")) {
                JOptionPane.showMessageDialog(this, "Meter number already exists.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField address;
    private de.wannawork.jcalendar.JCalendarComboBox birthday;
    private javax.swing.JPasswordField conf_password;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField meter;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
